services:
  rigel:
    build:
      context: ../../images/rigel
    image: local/rigel
    container_name: rigel
    restart: unless-stopped
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    group_add:
      - video
      - render
    command: >
      -a ${ALGO}
      -o ${POOL}
      -u ${WALLET}
      -w ${WORKER}
    networks:
      - proxy

networks:
  proxy:
    external: true
