services:
  rigel:
    build:
      context: ../../images/rigel
    image: local/rigel
    container_name: rigel
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
    command: >
      -a ${ALGO}
      -o ${POOL}
      -u ${WALLET}
      -w ${WORKER}
    networks:
      - proxy

networks:
  proxy:
    external: true
