services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:v0.8.9
    container_name: openwebui
    restart: unless-stopped

    environment:
      OLLAMA_BASE_URL: http://ollama:11434

    volumes:
      - openwebui-data:/app/backend/data

    networks:
      - proxy

    labels:
      traefik.enable: "true"
      traefik.docker.network: proxy
      traefik.http.routers.openwebui.rule: "Host(`ai.${DOMAIN}`)"
      traefik.http.routers.openwebui.entrypoints: "websecure"
      traefik.http.routers.openwebui.tls: "true"
      traefik.http.services.openwebui.loadbalancer.server.port: "8080"

volumes:
  openwebui-data:

networks:
  proxy:
    external: true
